//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod appointment;
pub mod calendar_entry;
pub mod course;
pub mod flashcard;
pub mod flashcard_reference;
pub mod module;
pub mod note;
pub mod notebook;
pub mod semester;
pub mod session;
pub mod settings;
pub mod tag;
pub mod taggable;
pub mod todo;
pub mod todo_reference;
pub mod user;
