//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::appointment::Entity as Appointment;
pub use super::calendar_entry::Entity as CalendarEntry;
pub use super::course::Entity as Course;
pub use super::flashcard::Entity as Flashcard;
pub use super::flashcard_reference::Entity as FlashcardReference;
pub use super::module::Entity as Module;
pub use super::note::Entity as Note;
pub use super::notebook::Entity as Notebook;
pub use super::semester::Entity as Semester;
pub use super::session::Entity as Session;
pub use super::settings::Entity as Settings;
pub use super::tag::Entity as Tag;
pub use super::taggable::Entity as Taggable;
pub use super::todo::Entity as Todo;
pub use super::todo_reference::Entity as TodoReference;
pub use super::user::Entity as User;
