//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use async_graphql::Enum;
use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "todostatus")]
#[graphql(name = "TodoStatus")]
pub enum Todostatus {
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "inprogress")]
    Inprogress,
    #[sea_orm(string_value = "pending")]
    Pending,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "todotype")]
#[graphql(name = "TodoType")]
pub enum Todotype {
    #[sea_orm(string_value = "assignment")]
    Assignment,
    #[sea_orm(string_value = "exam")]
    Exam,
    #[sea_orm(string_value = "general")]
    General,
}
