//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod appointments;
pub mod calendar_entries;
pub mod courses;
pub mod flashcard_references;
pub mod flashcards;
pub mod modules;
pub mod notebooks;
pub mod notes;
pub mod semesters;
pub mod sessions;
pub mod settings;
pub mod taggables;
pub mod tags;
pub mod todos;
pub mod todos_reference;
pub mod users;
