//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "modules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub et_cs: i32,
    #[sea_orm(column_type = "Float", nullable)]
    pub grade: Option<f32>,
    pub start_semester: String,
    pub end_semester: Option<String>,
    pub user_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::courses::Entity")]
    Courses,
    #[sea_orm(
        belongs_to = "super::semesters::Entity",
        from = "Column::EndSemester",
        to = "super::semesters::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Semesters2,
    #[sea_orm(
        belongs_to = "super::semesters::Entity",
        from = "Column::StartSemester",
        to = "super::semesters::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Semesters1,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
