//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::appointments::Entity as Appointments;
pub use super::calendar_entries::Entity as CalendarEntries;
pub use super::courses::Entity as Courses;
pub use super::flashcard_references::Entity as FlashcardReferences;
pub use super::flashcards::Entity as Flashcards;
pub use super::modules::Entity as Modules;
pub use super::notebooks::Entity as Notebooks;
pub use super::notes::Entity as Notes;
pub use super::semesters::Entity as Semesters;
pub use super::sessions::Entity as Sessions;
pub use super::settings::Entity as Settings;
pub use super::taggables::Entity as Taggables;
pub use super::tags::Entity as Tags;
pub use super::todos::Entity as Todos;
pub use super::todos_reference::Entity as TodosReference;
pub use super::users::Entity as Users;
