//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "todos")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub due_on: DateTime,
    pub user_id: String,
    pub course_id: Option<String>,
    #[sea_orm(column_type = "custom(\"enum_text\")")]
    pub r#type: String,
    #[sea_orm(column_type = "custom(\"enum_text\")")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::UserId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Courses,
    #[sea_orm(has_many = "super::todos_reference::Entity")]
    TodosReference,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::todos_reference::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TodosReference.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

